In [3]:
#all imports required

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from numpy import log2 as log
%matplotlib inline

In [ ]:
df_ecommerce = pd.read_csv("E-Commerce Shipping_data.csv", index_col=0)
df_ecommerce

In [ ]:
df_ecommerce.info()

In [ ]:
df_ecommerce.columns

Data Explorations:

Warehouse Block:

In [ ]:
df_ecommerce['Warehouse_block'].describe()

In [ ]:
sns.displot(df_ecommerce['Warehouse_block'])

#alle außer F(~3666) kommen gleich oft vor (~1800)

Mode of Shipment:

In [ ]:
df_ecommerce['Mode_of_Shipment'].describe()

In [ ]:
sns.displot(df_ecommerce['Mode_of_Shipment'])

#Ship 7462, Flight und Road beide ~1800

Customer Rating:

In [ ]:
df_ecommerce['Customer_rating'].describe()

#durchschnitt 2.99 mit hoher(?) standartabweichung von 1.4

In [ ]:
sns.displot(df_ecommerce['Customer_rating'])

#sagt uns garnix

Prior Purchases:

In [ ]:
df_ecommerce['Prior_purchases'].describe()

#durchschnitt 3.57 mit standartabweichung 1.52

In [ ]:
sns.displot(df_ecommerce['Prior_purchases'])

Customer Care Calls:

In [ ]:
df_ecommerce['Customer_care_calls'].describe()

# durchschnitt 4.05 mit standartabweichung 1.14

In [ ]:
sns.displot(df_ecommerce['Customer_care_calls'])

Cost of Product:

In [ ]:
df_ecommerce['Cost_of_the_Product'].describe()

In [ ]:
sns.displot(df_ecommerce['Cost_of_the_Product'])

Product Importance:

In [ ]:
df_ecommerce['Product_importance'].describe()

In [ ]:
sns.displot(df_ecommerce['Product_importance'])

#low 5297, medium ~4800, high ~900

Gender:

In [ ]:
df_ecommerce['Gender'].describe()

# Female 5545, Male 5454 also ~50/50

Discount offered: 

In [ ]:
df_ecommerce['Discount_offered'].describe()

In [ ]:
sns.displot(df_ecommerce['Discount_offered'])

#mehrheitlich(75%) weniger als 10%

Weight in gms:

In [ ]:
df_ecommerce['Weight_in_gms'].describe()

In [ ]:
sns.displot(df_ecommerce['Weight_in_gms'])

#viel wiegt unter 2000 und viel zwischen 4000 - 6000

#TODO wie viel genau und Zusammenhänge(?)

Reached on time:

In [ ]:
df_ecommerce['Reached.on.Time_Y.N'].describe()

In [ ]:
df_ontime = pd.read_csv("E-Commerce Shipping_data.csv", usecols=['ID','Reached.on.Time_Y.N'])
df_ontime.groupby(['Reached.on.Time_Y.N']).count()

#4436 sind nicht on time angekommen, 6563 sind es

Korrelation zwischen Customer Rating und Cost of Product:

In [ ]:
cost = 'Cost_of_the_Product'
rating = 'Customer_rating'
data = pd.concat([df_ecommerce[cost], df_ecommerce[rating]], axis=1)
f, ax = plt.subplots(figsize=(100, 20))
fig = sns.boxplot(x=cost, y=rating, data=data)
fig.axis(ymin=0, ymax=6)

# korreliert nicht

#TODO Nicht-Korrelation besser beweisen/veranschaulichen

Korrelation zwischen Customer Rating und Customer Calls:

In [ ]:
calls = 'Customer_care_calls'
rating = 'Customer_rating'
data = pd.concat([df_ecommerce[calls], df_ecommerce[rating]], axis=1)
f, ax = plt.subplots(figsize=(20, 10))
fig = sns.boxplot(x=cost, y=rating, data=data)
fig.axis(ymin=0, ymax=6)

#korreliert nicht

Korrelation von Costs:

Data Cleansing:

In [ ]:
df = pd.read_csv("E-Commerce Shipping_data.csv", index_col=0)
df

In [6]:
df.isnull().sum()

#daten vollständig

Warehouse_block        0
Mode_of_Shipment       0
Customer_care_calls    0
Customer_rating        0
Cost_of_the_Product    0
Prior_purchases        0
Product_importance     0
Gender                 0
Discount_offered       0
Weight_in_gms          0
Reached.on.Time_Y.N    0
dtype: int64

In [ ]:
#TODO vllt manche kategorien rausnehmen weil unwichtig ?

Data Transformation:

In [ ]:
#TODO alle Werte in numerische Werte umwandeln um sie miteinander zu vergleichen
#TODO dazu gehört 'Warehouse_block', 'Mode_of_Shipment', 'Product_importance', 'Gender'

In [ ]:
#replaces the values of Product imortance low, medium, high with 1, 2, 3
#df['Product_importance'] = df['Product_importance'].replace({'low':1, 'medium': 2, 'high': 3})
df

MultiLabelEncoder:

In [9]:
from sklearn.pipeline import Pipeline 
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder() #Initalization as shortcut 'le'

class MultiColumnLabelEncoder:
    def __init__(self,columns = None):
        self.columns = columns # array of column names to encode

    def fit(self,X,y=None):
        return self

    def transform(self,X):
        '''
        Transforms columns of X specified in self.columns using
        LabelEncoder(). If no columns specified, transforms all
        columns in X.
        '''
        output = X.copy()
        if self.columns is not None:
            for col in self.columns:
                output[col] = le.fit_transform(output[col])
        else:
            for colname,col in output.iteritems():
                output[colname] = le.fit_transform(col)
        return output

    def fit_transform(self,X,y=None):
        return self.fit(X,y).transform(X)

In [15]:
df = MultiColumnLabelEncoder(columns= ['Warehouse_block', 'Mode_of_Shipment', 'Product_importance', 'Gender']).fit_transform(df)
df

Warehouse_block  Mode_of_Shipment  Customer_care_calls   
ID                                                              
1                    3                 0                    4  \
2                    4                 0                    4   
3                    0                 0                    2   
4                    1                 0                    3   
5                    2                 0                    2   
...                ...               ...                  ...   
10995                0                 2                    4   
10996                1                 2                    4   
10997                2                 2                    5   
10998                4                 2                    5   
10999                3                 2                    2   

       Customer_rating  Cost_of_the_Product  Prior_purchases   
ID                                                             
1                    2                  177                3  \
2                    5                  216                2   
3                    2                  183                4   
4                    3                  176                4   
5                    2                  184                3   
...                ...                  ...              ...   
10995                1                  252                5   
10996                1                  232                5   
10997                4                  242                5   
10998                2                  223                6   
10999                5                  155                5   

       Product_importance  Gender  Discount_offered  Weight_in_gms   
ID                                                                   
1                       1       0                44           1233  \
2                       1       1                59           3088   
3                       1       1                48           3374   
4                       2       1                10           1177   
5                       2       0                46           2484   
...                   ...     ...               ...            ...   
10995                   2       0                 1           1538   
10996                   2       0                 6           1247   
10997                   1       0                 4           1155   
10998                   2       1                 2           1210   
10999                   1       0                 6           1639   

       Reached.on.Time_Y.N  
ID                          
1                        1  
2                        1  
3                        1  
4                        1  
5                        1  
...                    ...  
10995                    1  
10996                    0  
10997                    0  
10998                    0  
10999                    0  

[10999 rows x 11 columns]

Machine Learning:

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


predict whether the ordered product will be reached on time or not

In [18]:
x = df.drop(['Reached.on.Time_Y.N'], axis=1)
y = df['Reached.on.Time_Y.N']

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = 42)
x_train.shape, x_test.shape

((7369, 10), (3630, 10))

In [20]:
logreg = LogisticRegression(solver="liblinear", random_state = 42)
logreg.fit(x_train, y_train)

LogisticRegression(random_state=42, solver='liblinear')

In [28]:
logreg.coef_

array([[ 0.00146445,  0.00170327, -0.11917119,  0.03933185, -0.00199916,
        -0.07739301, -0.07844085,  0.01203105,  0.11235758, -0.00022761]])

In [29]:
logreg.intercept_

array([1.41663002])

In [ ]:
np.set_printoptions(threshold=np.inf)
logreg.predict(x)

In [21]:
y_pred_test = logreg.predict(x_test)
y_pred_test

array([1, 0, 0, ..., 0, 1, 1], dtype=int64)

In [22]:
logreg.predict_proba(x_test)[:,0]

array([0.04983499, 0.56079198, 0.5639277 , ..., 0.59354931, 0.0032177 ,
       0.05506053])

In [24]:
logreg.predict_proba(x_test)[:,1]

array([0.95016501, 0.43920802, 0.4360723 , ..., 0.40645069, 0.9967823 ,
       0.94493947])

In [26]:
print(accuracy_score(y_test, y_pred_test))


0.6366391184573003


In [27]:
y_pred_train = logreg.predict(x_train)
y_pred_train

print(accuracy_score(y_train, y_pred_train))

0.645270728728457


predict the cost of the product for the company